[package]
name = "git-schedule"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "git-schedule"
path = "src/main.rs"

[dependencies]
git-schedule-shared = { path = "../shared" }

anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
console.workspace = true
dialoguer.workspace = true
git2.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

regex = "1"
dirs = "5"
